name: pmeshlab Docker Image

on:
  push:
    branches: ["dev", "master"]

  pull_request:
    branches: ["dev", "master"]

jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker vanilla image
      run: make build_docker_vanilla
    - name: Build the Docker sandbox image
      run: make build_docker_sandbox
    - name: Upload the package
      run: pip install twine && tine upload dist/pmeshlab*.whl --skip-existing -u jcadic -p {{ secrets.PYPI }} 
